// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: member.sql

package membersdb

import (
	"context"
)

const findMemberByID = `-- name: FindMemberByID :one
SELECT id, email, name, created_at FROM members.member WHERE id = $1
`

func (q *Queries) FindMemberByID(ctx context.Context, id string) (MembersMember, error) {
	row := q.db.QueryRow(ctx, findMemberByID, id)
	var i MembersMember
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const saveMember = `-- name: SaveMember :exec
INSERT INTO members.member (id, email, name) VALUES ($1, $2, $3)
`

type SaveMemberParams struct {
	ID    string
	Email string
	Name  string
}

func (q *Queries) SaveMember(ctx context.Context, arg SaveMemberParams) error {
	_, err := q.db.Exec(ctx, saveMember, arg.ID, arg.Email, arg.Name)
	return err
}
