// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package membersdb

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type MembersMember struct {
	ID        string
	Email     string
	Name      string
	CreatedAt pgtype.Timestamptz
}
